Add matplotlib pgf example
escape2020/school2022 pull request #10
Opened 2022-06-18 17:15 UTC by maxnoe

2022-06-20 14:21 UTC, vuillaut commented
Wanna include that in a `matplotlib.md` blog post as well?

2022-06-21 09:13 UTC, vuillaut requested changes
add a file to the docs please

2022-06-21 11:44 UTC, maxnoe commented
Can we merge this here and do the matplotlib post in #30 ?

2022-06-21 12:16 UTC, vuillaut approved these changes

2022-06-21 12:16 UTC, merged