add astropy and scipy notebook and aux data
escape2020/school2022 pull request #15
Opened 2022-06-19 20:25 UTC by JouvinLea

Here are the scipy and tutorial notebook.

I have an issue to load the video in the scipy notebook since tonight (-:! Can anyone just test localy if it works for him ?

2022-06-19 20:31 UTC, vuillaut requested changes
I don't think the `.idea` folder belongs here

2022-06-19 20:31 UTC, vuillaut commented on astropy/solutions/.idea/.gitignore
> +/workspace.xml
I don't  think this file should be included

2022-06-19 20:32 UTC, vuillaut commented
Could you also add two files (one for each course) in `docs/content/posts` following the `demo.md` so that the content of the classes appear in https://escape2020.github.io/school2022/ please?

2022-06-20 08:14 UTC, JouvinLea commented
Do you have other comments @vuillaut ? otherwise you can merge.

2022-06-20 09:01 UTC, maxnoe commented
I think there is some copy and paste stuff going on in the Readme, the scipy one has references to astropy

2022-06-20 09:04 UTC, vuillaut commented on scipy/README.md
> +# Astropy
here

2022-06-20 11:55 UTC, maxnoe commented
@JouvinLea your last commit says "clean" but it actually adds the output to the notebook. Did you forget to run "Cell -> Remove All Output"?

2022-06-20 12:53 UTC, vuillaut approved these changes

2022-06-20 12:54 UTC, vuillaut commented
The `echo $HOME` won't work on windows but I think we can let this one go ;-)

2022-06-20 14:23 UTC, vuillaut commented
The `astropy_hands_on` notebook doesn't run to the end

2022-06-21 09:11 UTC, merged